In [ ]:
import numpy as np
a = np.array([(13,12,31,4) , (45,521,16,37)])
print("The array is : \n",a)
print("Max: ",a.max())
print("Min: ",a.min())
print("The sorted array:\n",np.sort(a))
mn=np.mean(a, dtype=np.float64)
print("The mean is : ",mn)
column_to_be_added = np.array([[15], [29]])
#a = np.insert(a, 0, column_to_be_added, axis=1)
arr = np.concatenate([a, column_to_be_added], axis=1)
print("The added array is :\n",arr)
print("The flipped array is:\n",np.flip(arr))
a2= np.array([(11,192,13,45,16) , (47,51,106,7,64)])
print("The second array:\n",a2)
print("The multiplication of the two matrices is:\n",arr*a2)

The array is : 
 [[ 13  12  31   4]
 [ 45 521  16  37]]
Max:  521
Min:  4
The sorted array:
 [[  4  12  13  31]
 [ 16  37  45 521]]
The mean is :  84.875
The added array is :
 [[ 13  12  31   4  15]
 [ 45 521  16  37  29]]
The flipped array is:
 [[ 29  37  16 521  45]
 [ 15   4  31  12  13]]
The second array:
 [[ 11 192  13  45  16]
 [ 47  51 106   7  64]]
The multiplication of the two matrices is:
 [[  143  2304   403   180   240]
 [ 2115 26571  1696   259  1856]]


In [ ]:
import pandas as pd
import numpy as np
n=np.random.randn(5)
index=['a','b','c','d','e']
s1=pd.Series(n,index=index)
j=np.random.randn(5)
index=['a','b','c','d','e']
s2=pd.Series(j,index=index)
print("The first series :\n",s1)
print("The second series :\n",s2)
ss=s1+s2
print("Add two Series:")
print(ss)
print("Subtract two Series:")
ss = s1 - s2
print(ss)
print("Multiply two Series:")
ss = s1 * s2
print(ss)
print("Divide Series1 by Series2:")
ss = s1 / s2
print(ss)

The first series :
 a    1.236654
b    0.624109
c    0.028596
d   -1.762601
e    0.350899
dtype: float64
The second series :
 a    0.576108
b    0.354485
c    2.352546
d    0.090814
e    2.185045
dtype: float64
Add two Series:
a    1.812763
b    0.978594
c    2.381142
d   -1.671787
e    2.535944
dtype: float64
Subtract two Series:
a    0.660546
b    0.269623
c   -2.323950
d   -1.853415
e   -1.834146
dtype: float64
Multiply two Series:
a    0.712447
b    0.221237
c    0.067273
d   -0.160069
e    0.766730
dtype: float64
Divide Series1 by Series2:
a     2.146565
b     1.760605
c     0.012155
d   -19.408932
e     0.160591
dtype: float64


In [ ]:
import pandas as pd
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(data=d)
print("Original DataFrame")
print(df)
i=2
s1 = df.iloc[:,i]
print("\n",(i+1),"column as a Series:\n",s1)


Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

 3 column as a Series:
 0     7
1     5
2     8
3    12
4     1
5    11
Name: col3, dtype: int64


In [ ]:
import pandas as pd
dict = {'Name':['Martha', 'Tim', 'Rob', 'Georgia'],
        'Maths':[87, 91, 97, 95],
        'Science':[83, 99, 84, 76]
       }

df = pd.DataFrame(dict)
df.loc[len(df.index)] = ['Amy', 89, 93]
print(df)

      Name  Maths  Science
0   Martha     87       83
1      Tim     91       99
2      Rob     97       84
3  Georgia     95       76
4      Amy     89       93


In [ ]:
import pandas as pd
subs=[]
dict={}
nosub=int(input("Enter the number of subjects: "))
for x in range (0,nosub):
  s=input("Enter the name of the subject: ")
  subs.append(s)
st=int(input("Enter the number of students :"))
for y in range (0,st):
  n=input("Enter the name of student "+str(y+1)+" : ")
  if y==0:
    dict["Name"]=[n]
  else:
    dict["Name"].append(n)
  for z in range (0,nosub):
    m=float(input("Enter the marks in "+subs[z]+" : "))
    if y == 0:
      dict[subs[z]]=[m]
    else:
      dict[subs[z]].append(m)
  att=int(input("Enter the number of attempts : "))
  if y == 0:
      dict["Attempts"]=[att]
  else:
      dict["Attempts"].append(att)

print(dict)
df = pd.DataFrame.from_dict(dict)
print(df)
nrs=int(input("Enter the name of the row which is to be display: "))
print(df.loc[nrs,:])
ncs=(input("Enter the name of the column from which to display: "))
print(df.loc[:,ncs])
print("The sum of the number of attempts is :",df["Attempts"].sum())

Enter the number of subjects: 3
Enter the name of the subject: SL
Enter the name of the subject: SAS
Enter the name of the subject: LIC
Enter the number of students :3
Enter the name of student 1 : Ojas
Enter the marks in SL : 70
Enter the marks in SAS : 65
Enter the marks in LIC : 75
Enter the number of attempts : 1
Enter the name of student 2 : Stan
Enter the marks in SL : 68
Enter the marks in SAS : 65
Enter the marks in LIC : 73
Enter the number of attempts : 1
Enter the name of student 3 : Harshal
Enter the marks in SL : 63
Enter the marks in SAS : 58
Enter the marks in LIC : 673
Enter the number of attempts : 2
{'Name': ['Ojas', 'Stan', 'Harshal'], 'SL': [70.0, 68.0, 63.0], 'SAS': [65.0, 65.0, 58.0], 'LIC': [75.0, 73.0, 673.0], 'Attempts': [1, 1, 2]}
      Name    SL   SAS    LIC  Attempts
0     Ojas  70.0  65.0   75.0         1
1     Stan  68.0  65.0   73.0         1
2  Harshal  63.0  58.0  673.0         2
Enter the name of the row which is to be display: 1
Name        Stan
SL  

In [ ]:
# import pandas
import pandas as pd

# create dataframe
df = pd.DataFrame({
  'Employs Name': ['Rishabh', 'Rahul', 'Suraj', 'Mukul', 'Vinit'],
  'Location': ['Saharanpur', 'Meerut', 'Saharanpur', 'Meerut', 'Saharanpur'],
  'Pay': [21000, 22000, 23000, 24000, 22000]})

# print dataframe
print("\n *** Original DataFrames ** \n")
print(df)


# create dictionaries
dicts = [{'Employs Name': 'Anuj', 'Location': 'Meerut', 'Roll No': 30000},
    {'Employs Name': 'Arun', 'Location': 'Saharanpur', 'Roll No': 32000}]

# print dictionaries
print("\n ** Dictionary ** ")
print(dicts)


# combined data
df = df.append(dicts, ignore_index=True, sort=False)

# print combined dataframe
print("\n\n ** Combined Data **\n")
print(df)



 *** Original DataFrames ** 

  Employs Name    Location    Pay
0      Rishabh  Saharanpur  21000
1        Rahul      Meerut  22000
2        Suraj  Saharanpur  23000
3        Mukul      Meerut  24000
4        Vinit  Saharanpur  22000

 ** Dictionary ** 
[{'Employs Name': 'Anuj', 'Location': 'Meerut', 'Roll No': 30000}, {'Employs Name': 'Arun', 'Location': 'Saharanpur', 'Roll No': 32000}]


 ** Combined Data **

  Employs Name    Location      Pay  Roll No
0      Rishabh  Saharanpur  21000.0      NaN
1        Rahul      Meerut  22000.0      NaN
2        Suraj  Saharanpur  23000.0      NaN
3        Mukul      Meerut  24000.0      NaN
4        Vinit  Saharanpur  22000.0      NaN
5         Anuj      Meerut      NaN  30000.0
6         Arun  Saharanpur      NaN  32000.0


<ipython-input-25-4b4d2f087a6e>:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dicts, ignore_index=True, sort=False)


In [ ]:
import pandas as pd
student_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'],
        'marks': [200, 210, 190, 222, 199]})

student_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'],
        'marks': [201, 200, 198, 219, 201]})

exam_data = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5', 'S7', 'S8', 'S9', 'S10', 'S11', 'S12', 'S13'],
        'exam_id': [23, 45, 12, 67, 21, 55, 33, 14, 56, 83, 88, 12]})

print("Original DataFrames:")
print(student_data1)
print(student_data2)
print(exam_data)

print("\nJoin first two said dataframes along rows:")
result_data = pd.concat([student_data1, student_data2])
print(result_data)

print("\nNow join the said result_data and df_exam_data along student_id:")
final_merged_data = pd.merge(result_data, exam_data, on='student_id')
print(final_merged_data)